import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.181.2/build/three.module.js";
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,5000),renderer=new THREE.WebGLRenderer({antialias:true}),root=document.getElementById("game3d");renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;root.appendChild(renderer.domElement);scene.background=new THREE.Color(0x8fb3bc);scene.fog=new THREE.Fog(0x8fb3bc,250,1800);
scene.add(new THREE.HemisphereLight(0xd8edf0,0x536044,2));const sun=new THREE.DirectionalLight(0xffe6bb,3);sun.position.set(-300,500,300);sun.castShadow=true;scene.add(sun);
const G=new THREE.Group();scene.add(G),M={ground:new THREE.MeshStandardMaterial({color:0x91ad72}),road:new THREE.MeshStandardMaterial({color:0x42484a}),dirt:new THREE.MeshStandardMaterial({color:0x8a765b}),house:new THREE.MeshStandardMaterial({color:0xd2c2a5}),roof:new THREE.MeshStandardMaterial({color:0x765346}),tree:new THREE.MeshStandardMaterial({color:0x477542}),water:new THREE.MeshStandardMaterial({color:0x5f9eae}),player:new THREE.MeshStandardMaterial({color:0x304e55}),skin:new THREE.MeshStandardMaterial({color:0xd8ad88})};
function B(x,y,z,w,h,d,m){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;G.add(q);return q}function tree(x,z,s=.7){B(x,3*s,z,1.2*s,6*s,1.2*s,new THREE.MeshStandardMaterial({color:0x684b36}));const q=new THREE.Mesh(new THREE.SphereGeometry(5*s,9,7),M.tree);q.position.set(x,9*s,z);q.castShadow=true;G.add(q)}
B(0,-2,0,3000,4,2200,M.ground);B(0,.02,-880,3000,1,400,M.water);
for(const r of [[0,0,3000,110],[0,300,3000,70],[-520,0,75,2200],[280,0,70,2200],[720,0,80,2200]])B(r[0],.02,r[1],r[2],.08,r[3],M.road);B(0,.02,-480,1700,.08,55,M.dirt);
for(let x=-1200;x<1200;x+=55)for(let z=-700;z<-470;z+=55)tree(x,z,.55);
for(let x=-900;x<850;x+=130)for(let z=80;z<650;z+=120)tree(x,z,.5);
for(let x=-900;x<850;x+=120)for(let z=70;z<650;z+=150){B(x,8,z,58,16,48,M.house);B(x,18,z,64,4,54,M.roof)}
const places=[["Plaza de las Infancias",-180,40],["Municipalidad",40,40],["Balneario Municipal",-700,-500],["Mirador La Virgen",1030,-650],["Dique Compensador",1250,-470],["Chacras",650,-620],["Bodega Patritti",180,-570],["Malma",520,-520],["Secreto Patagónico",820,-560],["Parque Industrial",1120,280]];
for(const [n,x,z] of places){B(x,5,z,48,10,48,new THREE.MeshStandardMaterial({color:0xe0d0ae}));}
const player=new THREE.Group();B(0,1.3,0,2.2,2.5,1.3,M.player).parent===player;const body=new THREE.Mesh(new THREE.BoxGeometry(2.2,2.5,1.3),M.player);player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.65,12,10),M.skin);head.position.y=2.3;player.add(head);G.add(player);player.position.set(-120,0,0);
const keys=new Set();let yaw=0,speed=9,time=480,money=2500,vehicle=false;
addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==="e")interact();if(e.key.toLowerCase()==="m")menu("map");if(e.key==="Escape")close()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));document.querySelectorAll("#touch button").forEach(b=>{b.onpointerdown=()=>keys.add(b.dataset.k);b.onpointerup=()=>keys.delete(b.dataset.k);b.onpointerleave=()=>keys.delete(b.dataset.k)});
function clock(){return String(Math.floor(time/60)%24).padStart(2,"0")+":"+String(Math.floor(time%60)).padStart(2,"0")}function toast(t){const h=document.getElementById("hint");h.textContent=t;h.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>h.classList.remove("show"),2200)}
function interact(){let n=places.map(p=>({p,d:Math.hypot(player.position.x-p[1],player.position.z-p[2])})).sort((a,b)=>a.d-b.d)[0];toast(n&&n.d<70?n.p[0]+" · Chañar":"Recorré libremente el territorio.")}
function menu(type="main"){const p=document.getElementById("panel");p.classList.remove("hidden");document.getElementById("panelTitle").textContent=type==="map"?"CHAÑAR — MUNDO":"SAN PATRICIO";document.getElementById("panelBody").innerHTML=type==="map"?'<div class="row"><span>Hora</span><b>'+clock()+'</b></div><div class="row"><span>Dinero</span><b>$'+money+'</b></div><div class="row"><span>Zona</span><b>'+zone()+'</b></div><p class="muted">Río, costa, chacras, centro, barrios y producción.</p>':'<button class="action" id="mmap">MAPA Y PROGRESO</button><button class="action" id="car">ENTRAR / SALIR DEL VEHÍCULO</button><p class="muted">Mundo abierto 3D: caminar, conducir, explorar e interactuar.</p>';document.getElementById("mmap")?.addEventListener("click",()=>menu("map"));document.getElementById("car")?.addEventListener("click",()=>{vehicle=!vehicle;speed=vehicle?22:9;toast(vehicle?"Vehículo: conducción activada":"A pie")})}
function close(){document.getElementById("panel").classList.add("hidden")}document.getElementById("menu").onclick=()=>menu();document.getElementById("close").onclick=close;
function zone(){return player.position.z<-450?"Costa y chacras":player.position.x>900?"Producción e industria":player.position.z>300?"Barrios":"Centro"}
function update(dt){let f=(keys.has("w")||keys.has("arrowup")?1:0)-(keys.has("s")||keys.has("arrowdown")?1:0),r=(keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0);if(f||r){const d=new THREE.Vector3(r,0,-f).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw);player.position.addScaledVector(d,speed*dt);player.rotation.y=Math.atan2(d.x,d.z);player.position.x=THREE.MathUtils.clamp(player.position.x,-1450,1450);player.position.z=THREE.MathUtils.clamp(player.position.z,-1000,1000)}time+=dt*7;document.getElementById("clock").textContent=clock();document.getElementById("money").textContent=Math.floor(money);document.getElementById("sector").textContent=zone();sun.position.x=Math.cos(time/120)*500;sun.position.z=Math.sin(time/120)*300}
function loop(){requestAnimationFrame(loop);update(.016);camera.position.lerp(player.position.clone().add(new THREE.Vector3(0,8,13)),.12);camera.lookAt(player.position.clone().add(new THREE.Vector3(0,1,0)));renderer.render(scene,camera)}loop();addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});