(()=>{"use strict";
const C=document.getElementById("game"),ctx=C.getContext("2d"),D=WORLD_DATA,$=id=>document.getElementById(id),keys=new Set(),SAVE="spc_life_v1";
const S={x:1210,y:1060,a:-Math.PI/2,money:2500,time:480,day:1,energy:100,mission:null,completed:[],activity:null,vehicle:null,ownedVehicles:[],home:"Casa inicial",rep:0,skills:{movilidad:1,trabajo:1,deporte:1,exploracion:1},weather:"despejado",fuel:100,nearNpc:null,inventory:[],stats:{km:0,interactions:0,earnings:0},discovered:[]};let cam={x:S.x,y:S.y},last=performance.now(),open=false,toastT;
function resize(){const d=Math.min(devicePixelRatio||1,2);C.width=innerWidth*d;C.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function clock(){return String(Math.floor(S.time/60)%24).padStart(2,"0")+":"+String(Math.floor(S.time%60)).padStart(2,"0")}function zone(){const z=D.zones.find(z=>S.x>=z.x&&S.x<z.x+z.w&&S.y>=z.y&&S.y<z.y+z.h);return z?z.n:"Chañar"}function toast(t){$("hint").textContent=t;$("hint").classList.add("show");clearTimeout(toastT);toastT=setTimeout(()=>$("hint").classList.remove("show"),2600)}
function nearest(){let b=null,bd=100;for(const p of D.places){const d=dist(S,p);if(d<bd){bd=d;b=p}}return b}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(S))}catch{}}function load(){try{const v=JSON.parse(localStorage.getItem(SAVE));if(v){Object.assign(S,v);S.skills=S.skills||{movilidad:1,trabajo:1,deporte:1,exploracion:1};S.ownedVehicles=S.ownedVehicles||[];S.discovered=S.discovered||[];S.stats=S.stats||{km:0,interactions:0,earnings:0}}}catch{}}
const MISS=[
{id:"tour",title:"Conocer Chañar",desc:"Descubrí tres lugares del territorio.",reward:700,need:3,type:"visit"},
{id:"delivery",title:"Un encargo del barrio",desc:"Llegá al Parque Industrial.",reward:900,need:1,type:"industrial"},
{id:"coast",title:"Una tarde en la costa",desc:"Llegá al Balneario Municipal.",reward:500,need:1,type:"coast"},
{id:"sport",title:"Moverse hace bien",desc:"Hacé una actividad deportiva.",reward:650,need:1,type:"sport"},
{id:"chacra",title:"Camino de producción",desc:"Llegá a las chacras.",reward:850,need:1,type:"chacra"}];
function start(id){const m=MISS.find(x=>x.id===id);S.mission={id:m.id,title:m.title,desc:m.desc,reward:m.reward,need:m.need,type:m.type,progress:0,seen:[]};close();toast("Nueva misión: "+m.title);save()}
function missionTick(){const m=S.mission;if(!m)return;const p=nearest();if(m.type==="visit"&&p&&!m.seen.includes(p.id)){m.seen.push(p.id);m.progress=m.seen.length;toast("Descubriste: "+p.n)}if(m.type==="industrial"&&S.x>2250&&S.y>1150)m.progress=1;if(m.type==="coast"&&p?.id==="balneario")m.progress=1;if(m.type==="sport"&&S.activity)m.progress=1;if(m.type==="chacra"&&p?.id==="chacra")m.progress=1;if(m.progress>=m.need){S.money+=m.reward;S.completed.push(m.id);toast("Misión completa  +$"+m.reward);S.mission=null;save()}}
function interact(){S.stats.interactions++;const p=nearest();const n=D.npcs.reduce((b,x)=>!b||dist(S,x)<dist(S,b)?x:b,null);if(n&&dist(S,n)<70){S.nearNpc=n;S.rep++;toast(n.name+": ¡Qué bueno verte por acá!");save();return}if(!p){toast("Explorá un poco más.");return}if(p.kind==="sport"){S.activity="sport";S.energy=Math.min(100,S.energy+12);S.money=Math.max(0,S.money-20);toast("Actividad deportiva completada.")}else if(p.kind==="work"){const gain=80+Math.floor(S.skills.trabajo*25);S.money+=gain;S.stats.earnings+=gain;S.skills.trabajo=Math.min(10,S.skills.trabajo+.05);toast("Trabajo realizado  +$"+gain)}else if(p.kind==="social"){S.rep++;toast("Encuentro en "+p.n+" · reputación +1")}else toast(p.n+" — "+p.desc);missionTick()}
function update(dt){let dx=(keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0),dy=(keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0);if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;S.a=Math.atan2(dy,dx);const sp=S.vehicle?360:190;S.x=Math.max(25,Math.min(D.width-25,S.x+dx*sp*dt));S.y=Math.max(25,Math.min(D.height-25,S.y+dy*sp*dt))}S.time+=dt*7;if(S.time>=1440){S.time-=1440;S.day++}S.energy=Math.max(0,S.energy-dt*(S.vehicle?.055:.1));S.fuel=Math.max(0,S.fuel-(S.vehicle?dt*.18:0));for(const n of D.npcs){n.x+=Math.cos(n.id*1.7)*n.speed*dt;n.y+=Math.sin(n.id*2.3)*n.speed*dt;n.x=Math.max(450,Math.min(2250,n.x));n.y=Math.max(680,Math.min(1950,n.y))}for(const c of D.cars){c.x+=Math.cos(c.a)*c.speed*dt;c.y+=Math.sin(c.a)*c.speed*dt;if(c.a===0&&c.x>D.width+20)c.x=-20;if(c.a===Math.PI/2&&c.y>D.height+20)c.y=-20}cam.x+=(S.x-cam.x)*Math.min(1,dt*6);cam.y+=(S.y-cam.y)*Math.min(1,dt*6);$("sector").textContent=zone();$("clock").textContent=clock();$("money").textContent=Math.floor(S.money);missionTick()}
function drawWeather(w,h){if(S.weather==="lluvia"){ctx.fillStyle="#6b7d8b33";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#b9d0df66";for(let i=0;i<70;i++){const x=(i*83+performance.now()*.2)%w,y=(i*47+performance.now()*.6)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+14);ctx.stroke()}}else if(S.weather==="nublado"){ctx.fillStyle="#4d596022";ctx.fillRect(0,0,w,h)}}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(innerWidth/2-cam.x,innerHeight/2-cam.y);ctx.fillStyle="#aabd7d";ctx.fillRect(0,0,D.width,D.height);
ctx.fillStyle="#75aab3";ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(D.width,0);ctx.lineTo(D.width,145);ctx.quadraticCurveTo(2300,190,1750,115);ctx.quadraticCurveTo(850,50,0,180);ctx.closePath();ctx.fill();ctx.fillStyle="#a88360";ctx.fillRect(0,590,D.width,70);
ctx.strokeStyle="#91a967";ctx.lineWidth=3;for(let x=500;x<2050;x+=35){ctx.beginPath();ctx.moveTo(x,170);ctx.lineTo(x,540);ctx.stroke()}
for(const r of D.roads){ctx.fillStyle=r.t==="rural"?"#8a7d61":"#4e5556";ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle="#d5c16c";ctx.lineWidth=2;if(r.w>r.h)for(let x=r.x+15;x<r.x+r.w;x+=45){ctx.beginPath();ctx.moveTo(x,r.y+r.h/2);ctx.lineTo(x+22,r.y+r.h/2);ctx.stroke()}else for(let y=r.y+15;y<r.y+r.h;y+=45){ctx.beginPath();ctx.moveTo(r.x+r.w/2,y);ctx.lineTo(r.x+r.w/2,y+22);ctx.stroke()}}
for(const h of D.houses){ctx.fillStyle="#d7c4a2";ctx.fillRect(h[0],h[1],74,52);ctx.fillStyle="#865f4c";ctx.beginPath();ctx.moveTo(h[0]-5,h[1]);ctx.lineTo(h[0]+37,h[1]-20);ctx.lineTo(h[0]+79,h[1]);ctx.fill()}
for(const t of D.trees){ctx.fillStyle="#477645";ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,7);ctx.fill();ctx.fillStyle="#6f5138";ctx.fillRect(t.x-2,t.y+t.r-1,4,9)}
for(const p of D.places){ctx.fillStyle=p.id===S.mission?.type?"#f2c84b":"#efe5c8";ctx.strokeStyle="#26342c";ctx.beginPath();ctx.arc(p.x,p.y,22,0,7);ctx.fill();ctx.stroke();ctx.fillStyle="#17221b";ctx.font="11px Arial";ctx.textAlign="center";ctx.fillText(p.n,p.x,p.y+39)}
for(const c of D.cars){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);ctx.fillStyle=["#263d49","#7d5d45","#3c5b42"][c.color];ctx.fillRect(-20,-9,40,18);ctx.fillStyle="#b7d0d0";ctx.fillRect(-4,-7,12,14);ctx.restore()}
for(const n of D.npcs){ctx.fillStyle="#684a3b";ctx.beginPath();ctx.arc(n.x,n.y-10,5,0,7);ctx.fill();ctx.fillStyle=n.job==="deporte"?"#b45f4d":"#63798a";ctx.fillRect(n.x-6,n.y-5,12,16)}
ctx.save();ctx.translate(S.x,S.y);ctx.rotate(S.a);ctx.fillStyle="#20252a";ctx.fillRect(-10,-14,20,28);ctx.fillStyle="#d8b28f";ctx.beginPath();ctx.arc(0,-16,7,0,7);ctx.fill();ctx.fillStyle="#d5b84e";ctx.fillRect(5,-4,5,7);ctx.restore();ctx.restore();drawWeather(innerWidth,innerHeight)}
function panel(type){open=true;$("panel").classList.remove("hidden");let title="SAN PATRICIO",html="";if(type==="map"){title="CHAÑAR — PROGRESO";html='<div class="row"><span>Día</span><b>'+S.day+'</b></div><div class="row"><span>Hora</span><b>'+clock()+'</b></div><div class="row"><span>Dinero</span><b>$'+Math.floor(S.money)+'</b></div><div class="row"><span>Energía</span><b>'+Math.floor(S.energy)+'%</b></div><div class="row"><span>Misiones</span><b>'+S.completed.length+'</b></div><p class="muted">Explorá libremente: río, bardas, chacras, centro, barrios y producción.</p>'}else if(type==="life"){title="VIDA Y PROGRESO";html="<div class=\"row\"><span>Movilidad</span><b>Nivel "+S.skills.movilidad+"</b></div><div class=\"row\"><span>Trabajo</span><b>Nivel "+S.skills.trabajo.toFixed(1)+"</b></div><div class=\"row\"><span>Deporte</span><b>Nivel "+S.skills.deporte+"</b></div><div class=\"row\"><span>Exploración</span><b>Nivel "+S.skills.exploracion+"</b></div><div class=\"row\"><span>Reputación</span><b>"+S.rep+"</b></div><p class=\"muted\">Tu progreso construye movilidad, experiencia, vínculos y conocimiento del territorio.</p>"}else if(type==="vehicles"){title="MOVILIDAD";html="<p>Tu movilidad abre el mundo.</p><button class=\"action\" data-car=\"bicicleta\">USAR BICICLETA — GRATIS</button><button class=\"action\" data-car=\"utilitario\">COMPRAR UTILITARIO — $1800</button><button class=\"action\" data-car=\"pickup\">COMPRAR PICKUP — $3200</button><div class=\"row\"><span>Combustible</span><b>"+Math.floor(S.fuel)+"%</b></div>"}else if(type==="missions"){title="ACTIVIDADES";for(const m of MISS){const done=S.completed.includes(m.id),active=S.mission?.id===m.id;html+='<div class="mission"><strong>'+m.title+(done?' ✓':'')+'</strong><div>'+m.desc+'</div><small>Recompensa: $'+m.reward+'</small>';if(!done&&!active)html+='<button class="action" data-mission="'+m.id+'">ACEPTAR</button>';if(active)html+='<div class="ok">En curso · '+m.progress+'/'+m.need+'</div>';html+='</div>'}}else{html='<button class="action" data-panel="map">MAPA Y PROGRESO</button><button class="action" data-panel="missions">MISIONES Y ACTIVIDADES</button><button class="action" data-panel="life">VIDA Y PROGRESO</button><button class="action" data-panel="vehicles">VEHÍCULOS</button><button class="action" data-save="1">GUARDAR PARTIDA</button><p class="muted">Mundo abierto inspirado en la libertad y densidad sistémica de GTA San Andreas, con una mirada centrada en vivir San Patricio del Chañar.</p>'}$("panelTitle").textContent=title;$("panelBody").innerHTML=html}
function close(){open=false;$("panel").classList.add("hidden")}
$("menu").onclick=()=>panel("menu");$("close").onclick=close;$("panelBody").onclick=e=>{if(e.target.dataset.mission){start(e.target.dataset.mission);return}if(e.target.dataset.panel){panel(e.target.dataset.panel);return}if(e.target.dataset.car){const c=e.target.dataset.car,cost=c==="utilitario"?1800:c==="pickup"?3200:0;if(c==="bicicleta"||S.money>=cost){if(cost)S.money-=cost;S.vehicle=c;if(!S.ownedVehicles.includes(c))S.ownedVehicles.push(c);S.skills.movilidad=Math.min(10,S.skills.movilidad+1);toast("Movilidad: "+c);save();panel("vehicles")}else toast("Todavía no alcanza el dinero.");return}if(e.target.dataset.save){save();toast("Partida guardada")}};
addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==="e")interact();if(e.key.toLowerCase()==="m")panel("map");if(e.key==="Escape")close()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll("#touch button").forEach(b=>{const k=b.dataset.k;b.onpointerdown=()=>keys.add(k);b.onpointerup=()=>keys.delete(k);b.onpointerleave=()=>keys.delete(k)});load();function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;if(!open)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();